/*
	EXERCICIO 4

	LISTE TODAS MULHERES NASCIDAS NO BRASIL E TENHAM A INICIAL J

*/

USE CADASTRO;

SELECT * FROM GAFANHOTOS;

SELECT * FROM GAFANHOTOS 
WHERE NACIONALIDADE like 'Brasil' AND SEXO = 'F' AND NOME LIKE 'J%'
ORDER BY NOME;
